// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7E7Ohp-Hnk2t1p4XjI4Ohz6wCuxs4Q8',
    appId: '1:1097195866695:web:4e535518c0e3201c4b7f62',
    messagingSenderId: '1097195866695',
    projectId: 'profilepage-aa1a6',
    authDomain: 'profilepage-aa1a6.firebaseapp.com',
    storageBucket: 'profilepage-aa1a6.appspot.com',
    measurementId: 'G-R8KPF1X66S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKI7SkGKI7ztoX603tFRI4wD44Bz1D6w',
    appId: '1:1097195866695:android:6a33d6c5b38689f64b7f62',
    messagingSenderId: '1097195866695',
    projectId: 'profilepage-aa1a6',
    storageBucket: 'profilepage-aa1a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxZQ5oGrbfvM2UAt8VoVJIfp-LipNwWg',
    appId: '1:1097195866695:ios:f46992f8302984004b7f62',
    messagingSenderId: '1097195866695',
    projectId: 'profilepage-aa1a6',
    storageBucket: 'profilepage-aa1a6.appspot.com',
    iosClientId: '1097195866695-dcrkcam59b22cefjrb1m1raqr4cr62mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyxZQ5oGrbfvM2UAt8VoVJIfp-LipNwWg',
    appId: '1:1097195866695:ios:f46992f8302984004b7f62',
    messagingSenderId: '1097195866695',
    projectId: 'profilepage-aa1a6',
    storageBucket: 'profilepage-aa1a6.appspot.com',
    iosClientId: '1097195866695-dcrkcam59b22cefjrb1m1raqr4cr62mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );
}
